{% set name = "lightning-cloud" %}
{% set version = "0.6.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/lightning_cloud-{{ version }}.tar.gz
  sha256: c44e0cde280e32d789ac1117118ce398839e576b7ed7244aaff38d9191e57fbc

build:
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation --ignore-installed --no-cache-dir -vv
  number: 0
  skip: true  # [py<37]

requirements:
  host:
    - pip
    - python
    - wheel
    - setuptools
  run:
    - python
    - fastapi
    - requests
    - rich
    - six
    - urllib3
    - uvicorn

test:
  imports:
    - lightning_cloud
    - lightning_cloud.__version__
    - lightning_cloud.env
    - lightning_cloud.login
    - lightning_cloud.openapi
    - lightning_cloud.rest_client
    - lightning_cloud.source_code
    - lightning_cloud.utils.data_connection
  commands:
    - pip check
    - python -c "from importlib.metadata import version; assert(version('{{ name }}')=='{{ version }}')"
  # Upstream tests are available on github but there is not pip package version there.
  requires:
    - pip

about:
  home: https://github.com/Lightning-AI/pytorch-lightning
  summary: Lightning AI Command Line Interface
  description: Lightning AI Command Line Interface
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  dev_url: https://github.com/Lightning-AI/pytorch-lightning
  doc_url: https://github.com/Lightning-AI/pytorch-lightning

extra:
  recipe-maintainers:
    - Borda
    - weiji14
