{% set name = "lightning-cloud" %}
{% set version = "0.5.31" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/lightning_cloud-{{ version }}.tar.gz
  sha256: a5a138f4abbeffe66ee476fb9a8d621befac0434ffeeeec1cc00ccd3d72ffc09

build:
  entry_points:
    - lightning_cloud=lightning_cloud.cli.__main__:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - click
    - fastapi
    - pyjwt
    - python >=3.7
    - requests
    - rich
    - six
    - urllib3
    - uvicorn
    - websocket-client

test:
  imports:
    - lightning_cloud
  commands:
    - pip check
    - lightning_cloud --help
  requires:
    - pip

about:
  home: https://lightning.ai
  summary: Lightning Cloud
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - Borda
    - weiji14
